[package]
name = "nusbtmc"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2"
nusb = "0.1"
thiserror = "1"
tracing = "0.1"

[dev-dependencies]
futures-lite = "2"
tracing-subscriber = "0.3"